spring.application.name=rotdb
spring.datasource.url=jdbc:postgresql://localhost:5432/rot_db
spring.datasource.username=wxrl
spring.datasource.password=Patricks8148!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
