--
-- PostgreSQL database dump
--

\restrict GrAGAbsA6xdUzaac5G4B1n1WPl2f1Wo6csb5EF2Vlns8wJPC2bREDNh7gJS9wP1

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: wxrl
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO wxrl;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: wxrl
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ability; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.ability (
    id bigint NOT NULL,
    adrenaline_cost integer,
    adrenaline_gain integer,
    channeled boolean,
    cooldown integer,
    level integer,
    name character varying(255),
    style character varying(255),
    weapon_type character varying(255),
    CONSTRAINT ability_weapon_type_check CHECK (((weapon_type)::text = ANY ((ARRAY['BOTH'::character varying, 'TWO_HANDED'::character varying, 'DUAL_WIELD'::character varying])::text[])))
);


ALTER TABLE public.ability OWNER TO wxrl;

--
-- Name: ability_hit; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.ability_hit (
    id bigint NOT NULL,
    binds boolean,
    can_crit boolean,
    hit_index integer,
    max double precision,
    min double precision,
    stuns boolean,
    weapon_type character varying(255),
    ability_id bigint,
    CONSTRAINT ability_hit_weapon_type_check CHECK (((weapon_type)::text = ANY ((ARRAY['BOTH'::character varying, 'TWO_HANDED'::character varying, 'DUAL_WIELD'::character varying])::text[])))
);


ALTER TABLE public.ability_hit OWNER TO wxrl;

--
-- Name: ability_hit_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

ALTER TABLE public.ability_hit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ability_hit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ability_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

ALTER TABLE public.ability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.equipment (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    name text NOT NULL,
    class character varying(255),
    slot character varying(255),
    tier integer,
    style character varying(255),
    type character varying(255),
    damagetier integer,
    accuracytier integer,
    strength double precision,
    ranged double precision,
    magic double precision,
    necromancy double precision,
    prayer double precision,
    requirements_raw text,
    req_strength integer,
    raw_infobox jsonb,
    effects text[],
    accuracy double precision,
    accuracy_tier integer,
    armour double precision,
    armour_damage_tier integer,
    armour_tier integer,
    attack_range double precision,
    damage double precision,
    damage_bonus double precision,
    damage_tier integer,
    defensive_bonus double precision,
    equippable boolean,
    ids character varying(255),
    images character varying(1000),
    invtier integer,
    level_requirement character varying(255),
    life double precision,
    members boolean,
    pvm_reduction double precision,
    pvp_reduction double precision,
    requirements character varying(255),
    speed double precision,
    versions character varying(255)
);


ALTER TABLE public.equipment OWNER TO wxrl;

--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

CREATE SEQUENCE public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.equipment_id_seq OWNER TO wxrl;

--
-- Name: equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: wxrl
--

ALTER SEQUENCE public.equipment_id_seq OWNED BY public.equipment.id;


--
-- Name: familiar; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.familiar (
    id bigint NOT NULL,
    attack_rate double precision,
    auto_damage double precision,
    name character varying(255)
);


ALTER TABLE public.familiar OWNER TO wxrl;

--
-- Name: familiar_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

ALTER TABLE public.familiar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.familiar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: familiar_scroll_effect; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.familiar_scroll_effect (
    id bigint NOT NULL,
    effect_name character varying(255),
    effect_value double precision,
    familiar_id bigint
);


ALTER TABLE public.familiar_scroll_effect OWNER TO wxrl;

--
-- Name: familiar_scroll_effect_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

ALTER TABLE public.familiar_scroll_effect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.familiar_scroll_effect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perk; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.perk (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    max_rank_standard integer,
    max_rank_ancient integer,
    is_weapon_gizmo boolean,
    is_armour_gizmo boolean,
    iw_armour_gizmo boolean,
    iw_weapon_gizmo boolean
);


ALTER TABLE public.perk OWNER TO wxrl;

--
-- Name: perk_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

CREATE SEQUENCE public.perk_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.perk_id_seq OWNER TO wxrl;

--
-- Name: perk_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: wxrl
--

ALTER SEQUENCE public.perk_id_seq OWNED BY public.perk.id;


--
-- Name: set_effect; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.set_effect (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    pieces integer NOT NULL
);


ALTER TABLE public.set_effect OWNER TO wxrl;

--
-- Name: set_effect_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

CREATE SEQUENCE public.set_effect_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.set_effect_id_seq OWNER TO wxrl;

--
-- Name: set_effect_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: wxrl
--

ALTER SEQUENCE public.set_effect_id_seq OWNED BY public.set_effect.id;


--
-- Name: spells; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.spells (
    id integer NOT NULL,
    name text NOT NULL,
    level_required integer,
    damage_scale double precision
);


ALTER TABLE public.spells OWNER TO wxrl;

--
-- Name: spells_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

CREATE SEQUENCE public.spells_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.spells_id_seq OWNER TO wxrl;

--
-- Name: spells_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: wxrl
--

ALTER SEQUENCE public.spells_id_seq OWNED BY public.spells.id;


--
-- Name: spells_staging; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.spells_staging (
    data jsonb
);


ALTER TABLE public.spells_staging OWNER TO wxrl;

--
-- Name: target; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.target (
    id bigint NOT NULL,
    affinity character varying(255),
    bindable boolean,
    defense integer,
    demon boolean,
    dragon boolean,
    name character varying(255),
    stunnable boolean,
    undead boolean,
    walkable boolean
);


ALTER TABLE public.target OWNER TO wxrl;

--
-- Name: target_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

ALTER TABLE public.target ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.target_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: targets; Type: TABLE; Schema: public; Owner: wxrl
--

CREATE TABLE public.targets (
    id bigint NOT NULL,
    title text NOT NULL,
    name text NOT NULL,
    size integer,
    lifepoints1 integer,
    lifepoints2 integer,
    armour1 integer,
    armour2 integer,
    defence1 integer,
    defence2 integer,
    aff_melee integer,
    aff_ranged integer,
    aff_magic integer,
    aff_weakness integer,
    weakness text,
    susceptibility text,
    primarystyle text,
    immune_to_poison boolean,
    immune_to_deflect boolean,
    immune_to_stun boolean,
    immune_to_drain boolean,
    raw_infobox jsonb
);


ALTER TABLE public.targets OWNER TO wxrl;

--
-- Name: targets_id_seq; Type: SEQUENCE; Schema: public; Owner: wxrl
--

CREATE SEQUENCE public.targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.targets_id_seq OWNER TO wxrl;

--
-- Name: targets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: wxrl
--

ALTER SEQUENCE public.targets_id_seq OWNED BY public.targets.id;


--
-- Name: equipment id; Type: DEFAULT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.equipment ALTER COLUMN id SET DEFAULT nextval('public.equipment_id_seq'::regclass);


--
-- Name: perk id; Type: DEFAULT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.perk ALTER COLUMN id SET DEFAULT nextval('public.perk_id_seq'::regclass);


--
-- Name: set_effect id; Type: DEFAULT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.set_effect ALTER COLUMN id SET DEFAULT nextval('public.set_effect_id_seq'::regclass);


--
-- Name: spells id; Type: DEFAULT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.spells ALTER COLUMN id SET DEFAULT nextval('public.spells_id_seq'::regclass);


--
-- Name: targets id; Type: DEFAULT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.targets ALTER COLUMN id SET DEFAULT nextval('public.targets_id_seq'::regclass);


--
-- Name: ability_hit ability_hit_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.ability_hit
    ADD CONSTRAINT ability_hit_pkey PRIMARY KEY (id);


--
-- Name: ability ability_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.ability
    ADD CONSTRAINT ability_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: familiar familiar_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.familiar
    ADD CONSTRAINT familiar_pkey PRIMARY KEY (id);


--
-- Name: familiar_scroll_effect familiar_scroll_effect_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.familiar_scroll_effect
    ADD CONSTRAINT familiar_scroll_effect_pkey PRIMARY KEY (id);


--
-- Name: perk perk_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.perk
    ADD CONSTRAINT perk_pkey PRIMARY KEY (id);


--
-- Name: set_effect set_effect_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.set_effect
    ADD CONSTRAINT set_effect_pkey PRIMARY KEY (id);


--
-- Name: spells spells_name_key; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.spells
    ADD CONSTRAINT spells_name_key UNIQUE (name);


--
-- Name: spells spells_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.spells
    ADD CONSTRAINT spells_pkey PRIMARY KEY (id);


--
-- Name: target target_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.target
    ADD CONSTRAINT target_pkey PRIMARY KEY (id);


--
-- Name: targets targets_pkey; Type: CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.targets
    ADD CONSTRAINT targets_pkey PRIMARY KEY (id);


--
-- Name: familiar_scroll_effect fkgs85ae3r2silfxqsf8la4mwy; Type: FK CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.familiar_scroll_effect
    ADD CONSTRAINT fkgs85ae3r2silfxqsf8la4mwy FOREIGN KEY (familiar_id) REFERENCES public.familiar(id);


--
-- Name: ability_hit fksy39e0j5g3inrxgjvvkky8t4v; Type: FK CONSTRAINT; Schema: public; Owner: wxrl
--

ALTER TABLE ONLY public.ability_hit
    ADD CONSTRAINT fksy39e0j5g3inrxgjvvkky8t4v FOREIGN KEY (ability_id) REFERENCES public.ability(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: wxrl
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict GrAGAbsA6xdUzaac5G4B1n1WPl2f1Wo6csb5EF2Vlns8wJPC2bREDNh7gJS9wP1

